// Source of truth for the Terms of Service shown at /terms-of-service.
// Edit THIS file to change the terms text - no component/layout code
// needs to change. Keep the '**Last Updated: ...**' line current whenever
// the content meaningfully changes.
const termsOfServiceContent = `# Terms of Service

**Last Updated: July 27, 2026**

## 1. Acceptance of Terms

These Terms of Service ("Terms") govern your use of Justice Genie (the "App"), an AI-powered legal information platform operated by Yaganti Subhash and Vemula Siri Mahalaxmi as an independent academic and portfolio project. By creating an account or using the App, you agree to these Terms. If you do not agree, please do not use Justice Genie.

## 2. What Justice Genie Is

Justice Genie provides:
- An AI chat assistant that answers general legal questions, with a focus on Indian law
- A case-strength analysis tool that gives an AI-generated assessment of a described situation
- An interactive legal-knowledge quiz with a leaderboard
- A library of reference law documents

## 3. Not Legal Advice — Please Read This Section Carefully

**Justice Genie is an educational and informational tool. It is not a law firm, does not employ licensed attorneys, and nothing generated by the App constitutes legal advice.**

- Responses are generated by an AI model (Google's Gemini) and may be incomplete, outdated, or incorrect. AI systems can make mistakes, including confidently stating incorrect information.
- The case-strength analysis feature provides an automated, non-professional estimate only. It is not a prediction of any real legal outcome and should never be the basis for a legal decision.
- Using Justice Genie does not create an attorney-client relationship of any kind.
- **For any real legal matter, you should consult a licensed advocate or lawyer qualified in your jurisdiction.** Do not rely on the App as a substitute for professional legal counsel, especially for time-sensitive, high-stakes, or complex matters.
- We are not liable for any decision made, or action taken or not taken, based on information provided by the App.

## 4. Eligibility

You must be at least 18 years old to create an account and use Justice Genie.

## 5. Your Account

- You are responsible for maintaining the confidentiality of your password and for all activity that occurs under your account.
- You may create an account using an email/password or by signing in with Google. Signing in with Google links your account to the email address Google confirms belongs to you.
- Notify us immediately at justicegenie2.0@gmail.com if you suspect unauthorized access to your account.
- You may delete your account at any time from the My Account page.

## 6. Acceptable Use

You agree not to:
- Use the App for any unlawful purpose, or to seek help facilitating illegal activity
- Attempt to gain unauthorized access to another user's account or data
- Harass, threaten, or abuse other users, or submit abusive content through the feedback or collaboration features
- Attempt to reverse-engineer, scrape, or extract data from the App at scale, or interfere with its normal operation (including attempting to bypass rate limits or security controls)
- Impersonate any person or entity, or misrepresent your affiliation with any person or entity
- Use automated tools (bots, scripts) to interact with the App outside of normal human use

We reserve the right to suspend or permanently disable accounts that violate these Terms.

## 7. Your Content

You retain ownership of the questions and content you submit to Justice Genie ("User Content"). By submitting User Content, you grant us a limited license to store, process, and transmit it (including to third-party AI providers, as described in our Privacy Policy) solely for the purpose of operating and improving the App.

You are responsible for the content of your own questions and feedback. Please do not submit content that is illegal, defamatory, or violates the rights of others.

## 8. Intellectual Property

The App's design, branding, quiz content, and underlying software are the property of the operators, except where otherwise noted (such as third-party reference law documents, which remain the property of their respective sources). You may not copy, reproduce, or redistribute the App or its content without permission.

## 9. Third-Party Services

The App relies on third-party services, including Google (Gemini AI and Sign-In), MongoDB Atlas, Cloudinary, Brevo, Vercel, and Render, as described in our Privacy Policy. We are not responsible for outages, errors, or issues originating from these third-party services, though we will make reasonable efforts to address their impact on the App.

## 10. Disclaimers

The App is provided "as is" and "as available," without warranties of any kind, express or implied, including but not limited to accuracy, reliability, or fitness for a particular purpose. We do not guarantee that the App will be uninterrupted, error-free, or secure at all times.

## 11. Limitation of Liability

To the fullest extent permitted by law, the operators of Justice Genie shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of, or inability to use, the App — including but not limited to reliance on any AI-generated legal information or case-strength analysis.

## 12. Termination

We may suspend or terminate your access to the App at our discretion if we believe you have violated these Terms, engaged in abusive behavior, or posed a security risk to the platform or other users. You may stop using the App and delete your account at any time.

## 13. Changes to These Terms

We may update these Terms as the App evolves. We will update the "Last Updated" date above when we do. Continued use of the App after changes means you accept the updated Terms.

## 14. Governing Law

These Terms are governed by the laws of India, without regard to conflict-of-law principles.

## 15. Contact Us

Questions about these Terms can be sent to:

**justicegenie2.0@gmail.com**
`;

export default termsOfServiceContent;
